application: acm
version: python-09-config
module : default
runtime: python27
api_version: 1
threadsafe: yes

instance_class : F1
handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest

handlers:
- url: /.*
  script: guestbook.app